---
title: "Cell Extract Analysis"
author: "Your Name"
date: "`r strftime(Sys.Date(), '%B %d %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, warning=FALSE, message = FALSE
  
)

library("tidyverse")
```

```{r load_data, include=FALSE}
# Load project settings
source(here::here("settings.R"))

# load output functions
source(file.path(functions.dir, "output.R"))

# load processed casy count data
df.casy <- read_output_csv("casy", "casy_counts_diameter")
```

Calculate the amount of cells broken during the beat beating and the lysis efficiency as the percentage broken cells over the total cells before lysis.

```{r}
df.cell.extracts <- df.casy %>%
  filter(sample_type != "MC") %>%
  # filter(sample_type %in% c("BBB", "ABB")) %>%
  select(-contains("diameter")) %>%
  pivot_wider(
    names_from = sample_type,
    values_from = cells_mL
  ) %>%
  mutate(
    broken_cells_mL = BBB - ABB,
    lysis_efficiency = broken_cells_mL / BBB,
  ) %>%
  left_join(
    df.casy %>% 
      filter(sample_type == "MC") %>% 
      select(sample_id, peak_diameter, median_diameter, mean_diameter),
    by = 'sample_id'
  )
```

Plot the number of broken cells per sample

```{r}
df.cell.extracts %>%
  ggplot(aes(x=sample_id, y=broken_cells_mL, fill=sample_id)) +
  geom_col() +
  scale_fill_viridis_d() +
  scale_y_log10(labels = function(.x) { scales::number(.x, big.mark = ".") }) +
  coord_flip() +
  labs(
    x = "Sample ID", fill = "Sample ID",
    y = bquote("log"[10]~"# Broken Cells (mL"^-1~")")
  )
```

Plot the lysis efficiency per sample

```{r}
df.cell.extracts %>%
  mutate(
    sample_id = reorder(sample_id, 1-lysis_efficiency)
  ) %>%
  ggplot(aes(x=sample_id, y=1-lysis_efficiency, fill=sample_id)) +
  geom_col() +
  scale_fill_viridis_d() +
  scale_y_continuous(labels = scales::percent) +
  coord_flip() +
  labs(
    x = "Sample ID", fill = "Sample ID",
    y = "Percentage Unbroken Cells [%]"
  )
```

## Export

```{r export_data}
# load output 
source(file.path(functions.dir, "output.R"))
  
cell.extracts.export.file.path <- df.cell.extracts %>% 
  select(sample_id, ABB, BBB, broken_cells_mL, lysis_efficiency, peak_diameter, mean_diameter) %>%
  write_output_csv("cell_extracts")
```

Data was exported to `r cell.extracts.export.file.path`

